#let glossary-entries = (
  // === TERMS ===
  (
    key: "cdf",
    short: "cdf",
    long: "Cumulated distribution function",
    description: [Gives $F(x) = P(X <= x)$; for a continuous RV, the area under the pdf up to $x$. Use $F(b) - F(a)$ for $P(a < X <= b)$. (Danish: _Fordelingsfunktion_)],
    group: "Terms",
  ),
  (
    key: "CI",
    short: "CI",
    long: "Confidence interval",
    description: [An interval computed from data that covers the true parameter (e.g. $mu$) with probability $1 - alpha$. The width reflects sample size and variability, not the probability that $mu$ is inside a specific computed interval. (Danish: _Konfidensinterval_)],
    group: "Terms",
  ),
  (
    key: "cont-rv",
    short: "continuous RV",
    long: "Continuous random variable",
    description: [A random variable taking values on a continuous scale (e.g. length, temperature). Probabilities are areas under the pdf; $P(X = x) = 0$ for any single point. (Danish: _Kontinuert stokastisk variabel_)],
    group: "Terms",
  ),
  (
    key: "correlation",
    short: "Correlation",
    description: [Sample statistic $r in [-1, 1]$ measuring the linear strength between two variables: $r = s_(x y)\/(s_x dot s_y)$. $|r| = 1$ means perfect linear relation; $r = 0$ means no linear relation (but non-linear dependence may still exist). (Danish: _Korrelation_)],
    group: "Terms",
  ),
  (
    key: "covariance",
    short: "Covariance",
    description: [Sample statistic $s_(x y) = frac(1, n-1) sum (x_i - overline(x))(y_i - overline(y))$ measuring joint linear variation of two variables. Unlike correlation, it is not scale-free. (Danish: _Kovarians_)],
    group: "Terms",
  ),
  (
    key: "F-dist",
    short: "$F$-distribution",
    description: [Ratio of two independent scaled $chi^2$ variables: $(U\/nu_1)\/(V\/nu_2) tilde F(nu_1, nu_2)$. Arises in ANOVA $F$-tests and the overall regression $F$-test. Always right-skewed; only upper-tail critical values are tabulated. (Danish: _F-fordelingen_)],
    group: "Terms",
  ),
  (
    key: "IQR",
    short: "IQR",
    long: "Inter Quartile Range",
    description: [Middle 50 % spread of a sample: $"IQR" = Q_3 - Q_1$. Robust to outliers unlike the range. (Danish: _Interkvartil bredde_)],
    group: "Terms",
  ),
  (
    key: "median",
    short: "Median",
    description: [Middle value of an ordered sample ($Q_2 = q_(0.5)$). Robust to outliers; preferred over the mean for skewed data. (Danish: _Median / stikprøvemedian_)],
    group: "Terms",
  ),
  (
    key: "pdf",
    short: "pdf",
    long: "Probability density function",
    description: [Non-negative function with $integral_(-oo)^(oo) f(x) dif x = 1$; $f(x)$ itself is not a probability. The probability of an interval is the area: $P(a < X <= b) = integral_a^b f(x) dif x$.],
    group: "Terms",
  ),
  (
    key: "quantile",
    short: "Quantile",
    description: [Value $q_p$ such that a proportion $p$ of observations fall below it; equivalently, the inverse cdf at $p$. (Danish: _Fraktil / stikprøvefraktil_)],
    group: "Terms",
  ),
  (
    key: "quartile",
    short: "Quartile",
    description: [One of five values ($Q_0, Q_1, Q_2, Q_3, Q_4$) at $p = 0, 0.25, 0.5, 0.75, 1$ dividing the data into four equal parts. (Danish: _Kvartil_)],
    group: "Terms",
  ),
  (
    key: "sample-var",
    short: "Sample variance",
    description: [$s^2 = frac(1, n-1) sum (x_i - overline(x))^2$; the empirical variance using $n-1$ (Bessel's correction) to obtain an unbiased estimator of $sigma^2$. (Danish: _Empirisk varians / stikprøvevarians_)],
    group: "Terms",
  ),
  (
    key: "sample-mean",
    short: "Sample mean",
    description: [$overline(x) = frac(1,n) sum_(i=1)^n x_i$; the arithmetic average. Unbiased estimator of the population mean $mu$. (Danish: _Stikprøvegennemsnit_)],
    group: "Terms",
  ),
  (
    key: "sd",
    short: "Standard deviation",
    description: [Square root of the variance: $s = sqrt(s^2)$ (sample) or $sigma = sqrt(sigma^2)$ (population). Has the same units as the data; more interpretable than the variance. (Danish: _Standardafvigelse_)],
    group: "Terms",
  ),
  // === ACRONYMS ===
  (
    key: "ANOVA",
    short: "ANOVA",
    long: "Analysis of Variance",
    description: [Statistical procedure for comparing means of $k >= 2$ groups via $F$-tests on between- and within-group sums of squares. One-way: one factor; two-way: two factors (treatment + block).],
    group: "Acronyms",
  ),
  (
    key: "CLT",
    short: "CLT",
    long: "Central Limit Theorem",
    description: [States that $overline(X)$ is approximately $N(mu, sigma^2\/n)$ for large $n$, regardless of the population shape. The approximation is considered good for $n >= 30$.],
    group: "Acronyms",
  ),
  (
    key: "CV",
    short: "CV",
    long: "Coefficient of Variation",
    description: [Dimensionless measure of relative spread: $"CV" = s\/overline(x)$. Useful for comparing variability across different scales.],
    group: "Acronyms",
  ),
  (
    key: "LSD",
    short: "LSD",
    long: "Least Significant Difference",
    description: [$"LSD"_alpha = t_(1-alpha\/2) sqrt(2 dot "MSE"\/m)$ where $m$ is the group size. A post-hoc threshold: a pairwise mean difference $|overline(y)_i - overline(y)_j| > "LSD"$ is declared significant.],
    group: "Acronyms",
  ),
  (
    key: "OLS",
    short: "OLS",
    long: "Ordinary Least Squares",
    description: [Regression estimator that minimises $"SSE" = sum_i (y_i - hat(y)_i)^2$. Under the Gauss–Markov assumptions gives the BLUE (Best Linear Unbiased Estimator). Implemented by `smf.ols(...).fit()`.],
    group: "Acronyms",
  ),
  (
    key: "SE",
    short: "SE",
    long: "Standard Error",
    description: [Standard deviation of a sampling distribution; e.g. $"SE"_(overline(x)) = s\/sqrt(n)$ for the sample mean, or $"SE"_(hat(p)) = sqrt(hat(p)(1-hat(p))\/n)$ for a proportion.],
    group: "Acronyms",
  ),
)
